INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 1', 38.28);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 2', 40.02);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 3', 17.56);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 4', 38.42);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 5', 30.00);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 6', 20.00);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 7', 13.20);
INSERT INTO PRODUCT (PRODUCT_NAME, WEIGHT) VALUES ('TEST PRODUCT 8', 132.33);