FROM road/ubuntu_java8

ADD ./support/hystrix-dashboard/build/libs/support-hystrix-dashboard.jar app.jar

EXPOSE 7979

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]