FROM road/ubuntu_java8

ADD ./server/discovery/build/libs/server-discovery.jar app.jar

EXPOSE 8761

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=peer1", "-jar", "/app.jar"]