INSERT INTO RECOMMENDATION (PRODUCT_ID, AUTHOR, RATE, CONTENT) VALUES (1, 'user', 2, 'TEST RECOMMENDATION 1');
INSERT INTO RECOMMENDATION (PRODUCT_ID, AUTHOR, RATE, CONTENT) VALUES (2, 'user', 3, 'TEST RECOMMENDATION 2');
INSERT INTO RECOMMENDATION (PRODUCT_ID, AUTHOR, RATE, CONTENT) VALUES (3, 'user', 1, 'TEST RECOMMENDATION 3');
INSERT INTO RECOMMENDATION (PRODUCT_ID, AUTHOR, RATE, CONTENT) VALUES (2, 'user', 4, 'TEST RECOMMENDATION 4');
INSERT INTO RECOMMENDATION (PRODUCT_ID, AUTHOR, RATE, CONTENT) VALUES (1, 'user', 5, 'TEST RECOMMENDATION 5');
INSERT INTO RECOMMENDATION (PRODUCT_ID, AUTHOR, RATE, CONTENT) VALUES (4, 'user', 2, 'TEST RECOMMENDATION 6');